version: 2.1
orbs:
  node: circleci/node@5.0.0

executors:
  linux-arm:
    machine:
      image: ubuntu-2004:202101-01

commands:
  install-npm:
    steps:
      - node/install:
          install-yarn: true
          node-version: "16.13.2"
  
  set-npm-config:
    steps:
      - run:
          name: Set NPM config
          command: npm config set //npm.pkg.github.com/:_authToken=${NPM_TOKEN}
  
  install-dependencies:
    steps:
      - run:
          name: Install Dependencies
          command: yarn install --non-interactive --frozen-lockfile
  
  publish-electron-app:
    steps:
      - run:
          name: Publish
          command: yarn run publish
  
  yarn-make:
    steps:
      - run:
          name: Make Package
          command: yarn run make

jobs:
  publish-electron-app-linux-arm:
    executor: linux-arm
    resource_class: arm.medium
    working_directory: ~/repo
    steps:
      - install-npm
      - run:
          name: Install dpkg and fakeroot
          command: |
            sudo apt-get update -y
            sudo apt-get install -y dpkg fakeroot rpm
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - set-npm-config
      - install-dependencies
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - publish-electron-app

workflows:
  version: 2
  deploy-linux-arm:
    jobs:
      - publish-electron-app-linux-arm:
          filters: &tag
            tags:
              only: /^v[0-9]+(\.[0-9]+)*-linux-arm$/
            branches:
              ignore: /.*/
